### ISSUE TITLE
Issue with code in 

### ISSUE THREAD

**Issue by cjlyons81** [logstash-plugins/logstash-output-elasticsearch#940]
- Version:  Logstash 7.6.2
- Operating System: Oracle Linux 7.x
- Config File (if you have sensitive info, please remove it):

> elasticsearch {
>     id => "ES_OUT"
>     hosts => [...]
>     ssl => true
>     cacert => "..."
>     password => "..."
>     user => "..."
>     action => "%{[@metadata][action]}"
>     upsert => "true"  
>    #doc_as_upsert => true
>     retry_on_conflict => 10
>     document_type => "_doc"
>     index => "%{[@metadata][index]}"
>     document_id => "%{[@metadata][doc_id]}"
>   }

- Sample Data:
- Steps to Reproduce:

Scenarios:
1.) **action** set to explicit "update" and **doc_as_upsert** set to boolean true (result >  upsert **succeeds**)

2.) **action** set to sprintf "update" and **doc_as_upsert** set to boolean true (result > upsert **fails** with response "document doesn't exists")

3.) **action** set to explicit "update" and **upsert** set to string "true" (result > upsert **fails** with response "document doesn't exists")

4.) **action** set to springf "update" and **upsert** set to string "true" (result > upsert **fails** with response "document doesn't exists")

**What I did to fix the issue:**  Hard for me to tell what the objective is with the upsert parameter (perhaps just replacing doc_as_upsert) but on the surface the root of the problem is in http_client.rb (update_action_builder) lines 423-427.

> if @options[:doc_as_upsert]
>       source['doc_as_upsert'] = true
> else
>       source['upsert'] = args.delete(:_upsert) if args[:_upsert]
> end

**There are two problems:**
1.) When you attempt to use sprintf to create a dynamic action the doc_as_upsert parameter set in your config is never honored.  Not sure if this is part of the whole default options evaluation but @options[:doc_as_upsert] always evaluates to nil when attempted.  I tried to trace through the code but had to give up for the sake of time. 

2.) If you decide to try the upsert parameter it does capture the value set in the config but it's adding "upsert": true which doesn't appear to be an expected key within elasticsearch.
[https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update.html#doc_as_upsert](url)

**The fix I implemented:**
Updated the code above to read

> if @options[:doc_as_upsert]
>       source['doc_as_upsert'] = true
> else
>       source['doc_as_upsert'] = args.delete(:_upsert) if args[:_upsert]
> end

Given that the two options are still available and show in the documentation it would be nice if the code recognized the doc_as_upsert value even when action leverages sprintf in the config.  

Thanks!

**Comment by cjlyons81** [comment]
OK so I had to make another change to accommodate the retry logic.  Because the upsert parameter gets added to args (which if left causes error code 400) it needs to be removed for sending to ES.  When this is done if you get 429 or some other retriable error, that value is now gone from args so the update fails as doc_as_upsert is not set.  My very quick solution was to simply add to @options the first time and then make sure I remove the value from args for new events.  This is certainly not the appropriate way to do this, if you have time to look into it please let me know what you find.  

```
        if @options[:doc_as_upsert]
          source['doc_as_upsert'] = true
          args.delete(:_upsert) if args[:_upsert]
        else
         @options[:doc_as_upsert] = args.delete(:_upsert) if args[:_upsert]
         source['doc_as_upsert'] = @options[:doc_as_upsert]
        end
```

**Comment by alexnikolis** [comment]
I am experiencing this with Logstash 7.9.

Looks like this has been fixed before? 
https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/239

**Comment by enodr** [comment]
I can confirm the bug is still there. If action is dynamic string then doc_as_upsert => true is ignored; Looks like interpolation or evaluation of action is done too late somewhere in the code thus dropping doc_as_upsert?

**Comment by rcrichton** [comment]
Does anyone have a workaround for this? This appears to still be an issue.

**Comment by rcrichton** [comment]
Well, my workaround was to do this, but it sucks :(

```
output {
  # workaround because of this: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/940
  if [action] == "update" {
    elasticsearch {
      hosts => [ "es-analytics:9200" ]
      index => "fhir-enrich-%{[@metadata][lc_resourceType]}"
      document_id => "%{[resource][resourceType]}/%{[resource][id]}"
      action => "update"
      doc_as_upsert => true
    }
  }

  if [action] == "delete" {
    elasticsearch {
      hosts => [ "es-analytics:9200" ]
      index => "fhir-enrich-%{[@metadata][lc_resourceType]}"
      document_id => "%{[resource][resourceType]}/%{[resource][id]}"
      action => "delete"
      doc_as_upsert => true
    }
  }
}
```
